server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: springstudent
    password: springstudent
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to The Cards Development API"
  contactDetails:
    name: "Youness Bourgui"
    email: "younessbourgui@gmail.com"
    job: "Backend Java Dev"
  onCallSupport:
    - +212678213183