FROM openjdk:22-jdk-oracle
LABEL "org.opencontainers.image.authors"="eazybytes.com"
COPY target/cards-0.0.1-SNAPSHOT.jar cards-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","cards-0.0.1-SNAPSHOT.jar"]
