

build:
  version: "1.0"


accounts:
  message: "Welcome to Yassine accounts related Production APIs "
  contactDetails:
    name: "Yassine Bourgui - Product Owner"
    email: "yassinebourgui@gmail.com"
  onCallSupport:
    - (212) 678213183