


build:
  version: "1.0"

cards:
  message: "Welcome to The Cards Production API"
  contactDetails:
    name: "Sara Bourgui"
    email: "sarabourgui@gmail.com"
    job: "Product Owner"
  onCallSupport:
    - +212678213188