

build:
  version: "3.0"

loans:
  message: "Welcome to The Loans Development APIs"
  contactDetails:
       name: "Youness Bourgui"
       email: "younessbourgui@gmail.com"
       job: "Backend Java Dev"
  onCallSupport:
    - +212678213183

